version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    networks:
      - inception
    restart: always

  wordpress:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        MDP_WPUSR: ${MDP_WPUSR}
        MDP_WPADM: ${MDP_WPADM}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        NICK_WPUSR: ${NICK_WPUSR}
        NICK_WPADM: ${NICK_WPADM}
        MAIL_USR: ${MAIL_USR}
        MAIL_ADM: ${MAIL_ADM}
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
